#version: "3.9"
#
#services:
#  app:
#    build:
#      context: .
#    env_file:
#      - .env
#    ports:
#      - "5555:5500"
#    volumes:
#      - ./backend:/app
#      - /app/node_modules
#    restart: on-failure
#    command: >
#      sh -c "npm start"
#
#  db:
#    image: postgres
#    env_file:
#      - .env
#    volumes:
#      - ./postgresql-init.js:/docker-entrypoint-initdb.d/postgresql-init.js
#      - ./postgresql_db:/data/db
#    ports:
#      - "5433:5432"
#    restart: on-failure
##
##  web:
##    image: nginx:alpine
##    ports:
##      - "80:80"
##    restart: on-failure
##    volumes:
##      - ./task_manager_for_true_global/nginx.conf:/etc/nginx/conf.d/default.conf
##      - ./task_manager_for_true_global/client:/usr/share/nginx/html
